data:
  wikipedia:
    site: "en.wikipedia.org"
    api_rate_limit: 200
    cache_ttl: 3600

preprocessing:
  embeddings:
    model: "all-MiniLM-L6-v2"
    batch_size: 32
  graph:
    similarity_threshold: 0.7

models:
  clustering:
    method: "agglomerative"
    n_clusters: 100
    random_state: 42
  neighbors:
    n_neighbors: 10
    algorithm: "auto"


